### PR TITLE
Retry get topic after creating topic

### LINKED ISSUE #114: Retry get topic after creating in create topic Kafka REST implementation
We try to get the topic as soon as it is created in our internal Kafka REST implementation - https://github.com/confluentinc/ide-sidecar/blob/main/src/main/java/io/confluent/idesidecar/restapi/kafkarest/TopicManagerImpl.java#L53-L57, this has been shown to sometimes fail in our tests and adding a retry here will make the implementation more robust. 

This is recommended in the Javadoc for `UnknownTopicOrPartitionException` as well, "This exception is retriable because the topic or partition might subsequently be created." (https://kafka.apache.org/20/javadoc/org/apache/kafka/common/errors/UnknownTopicOrPartitionException.html)

### PR DESCRIPTION
**Pull request by rohitsanj**
## Summary of Changes

Resolves #114 

This first manifested as flakiness in our integration tests. We need to retry the get topic operation after creating a topic.

### CODE REVIEW

File: src/main/java/io/confluent/idesidecar/restapi/kafkarest/TopicManagerImpl.java [hunk 1]
```diff
@@ -54,7 +55,15 @@ public Uni<TopicDescription> createKafkaTopic(
...
             createTopicRequestData.getTopicName(),
             false
-        ));
+            )
+            // The topic may not be immediately available after creation, so we retry a few times
+            // This is also recommended in the Javadoc for UnknownTopicOrPartitionException
+            // "This exception is retryable because the topic or partition might
+            // subsequently be created."
+            .onFailure(UnknownTopicOrPartitionException.class)
+            .retry()
```
Comment (rhauch) [inline src/main/java/io/confluent/idesidecar/restapi/kafkarest/TopicManagerImpl.java:64]: Can we add a delay for the retries?

Comment (rohitsanj) [reply src/main/java/io/confluent/idesidecar/restapi/kafkarest/TopicManagerImpl.java:64]: Added exp backoff

File: src/main/java/io/confluent/idesidecar/restapi/kafkarest/TopicManagerImpl.java [hunk 2]
```diff
@@ -54,7 +56,18 @@ public Uni<TopicDescription> createKafkaTopic(
...
+            // Exponential backoff with a max of 3 retries
+            // Initial delay of 150ms, max delay of 1s
+            .withBackOff(Duration.ofMillis(150), Duration.ofMillis(1000))
```
Comment (rhauch) [inline src/main/java/io/confluent/idesidecar/restapi/kafkarest/TopicManagerImpl.java:68]: Let's merge this as-is (this is only a test), but in the future I'd do something like to make it more readable:
```suggestion
            .withBackOff(Duration.ofMillis(150), Duration.ofSeconds(1))
```

**Review by rhauch — APPROVED** [review]
LGTM. Thanks for adding the backoff.
