### PR TITLE
Do not reconnect to CCloud Language Service when session is closed

### LINKED ISSUE #411: Do not reconnect to CCloud Language Service when session is closed
The CCloud Language Service closes the WebSocket session when, for instance, an invalid message is sent. At the moment, the Language Service proxy [automatically reconnects](https://github.com/confluentinc/ide-sidecar/blob/main/src/main/java/io/confluent/idesidecar/websocket/proxy/FlinkLanguageServiceProxyClient.java#L82-L111) when the session is closed unexpectedly. This might swallow some errors and hide them from the extension. As a consequence, we want to remove the reconnection functionality from the proxy, so that the extension can take care of it.

### PR DESCRIPTION
**Pull request by flippingbits**
## Summary of Changes

This change delegates the handling of reconnection attempts from the sidecar-provided CCloud language service proxy to the extension-side WebSockets client.

Fixes #411

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

- Tests:
    - [ ] Added new
    - [x] Updated existing
    - [ ] Deleted existing
- [x] Have you validated this change locally against a running instance of the Quarkus dev server?
    ```shell
    make quarkus-dev
    ```
- [x] Have you validated this change against a locally running native executable?
    ```shell
    make mvn-package-native && ./target/ide-sidecar-*-runner
    ```

### CODE REVIEW

File: src/test/java/io/confluent/idesidecar/websocket/resources/FlinkLanguageServiceProxyTest.java [hunk 1]
```diff
@@ -131,7 +132,7 @@ void setup() {
         .thenReturn(mockedConnection);
   }
 
-  @Test
+  @RetryingTest(maxAttempts = 3)
```
Comment (flippingbits) [inline src/test/java/io/confluent/idesidecar/websocket/resources/FlinkLanguageServiceProxyTest.java:135]: Marked this test as retryable until https://github.com/confluentinc/ide-sidecar/issues/404 has been resolved.

**Review by rohitsanj — APPROVED** [review]
LGTM
