### PR TITLE
fix: Do not use `Path.of` when handling URIs

### LINKED ISSUE #412: Error 500 responses from `GET /subjects`: `Invalid URI: https://psrc-....confluent.cloud`
Originally from https://github.com/confluentinc/vscode/issues/1639

Possibly related to this section if it's expecting a file path?: https://github.com/confluentinc/ide-sidecar/blob/121d0d086ec98dc36146c987c4bf738cf281b9b1/src/main/java/io/confluent/idesidecar/restapi/util/UriUtil.java#L71-L74

### PR DESCRIPTION
**Pull request by flippingbits**
## Summary of Changes

This change removes the usage of `Path.of` when handling URIs. It's not meant to be used for URIs and seems to cause problems on Windows, because Windows doesn't allow question marks in path names. This change also adds a few log statements to the `UriUtil` so that we can better debug potential future issues.

Fixes #412

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

- Tests:
    - [ ] Added new
    - [ ] Updated existing
    - [ ] Deleted existing
- [x] Have you validated this change locally against a running instance of the Quarkus dev server?
    ```shell
    make quarkus-dev
    ```
- [ ] Have you validated this change against a locally running native executable?
    ```shell
    make mvn-package-native && ./target/ide-sidecar-*-runner
    ```

### CODE REVIEW

File: src/main/java/io/confluent/idesidecar/restapi/util/UriUtil.java [hunk 1]
```diff
@@ -68,19 +69,14 @@ public String combine(String baseUrl, String relativePath) {
...
-
       URI relativeUri = new URI(relativePath);
 
       // Resolve the relative URI against the base URI
       URI resolvedUri = baseUri.resolve(relativeUri);
-
       // Return the resolved URI as a string
       return resolvedUri.toString();
     } catch (URISyntaxException e) {
+      Log.error("Could not combine invalid URIs", e);
```
Comment (Cerchie) [inline src/main/java/io/confluent/idesidecar/restapi/util/UriUtil.java:79]: these will be nice downstream improvements

**Review by Cerchie — APPROVED** [review]
LGTM upon CI check passing
